### ISSUE TITLE
NGI Project: proximity_matcher_webservice

### ISSUE THREAD

**Issue by fricklerhandwerk** [ngi-nix/ngipkgs#68]
- source: https://github.com/armijnhemel/proximity_matcher_webservice

There is a concrete build failure with the development shell to be fixed, which was [introduced in a PR](https://github.com/armijnhemel/proximity_matcher_webservice/pull/3) from Summer of Nix last year.

Steps to reproduce:

```console
git clone https://github.com/armijnhemel/proximity_matcher_webservice
cd proximity_matcher_webservice
nix-shell
```

Same for `nix develop`.

<details><summary>Build log</summary>

```log
Traceback (most recent call last):
File "/nix/store/5n0n79zxpikzj3cdx9ympanlap9pwp68-python3.10-pip-22.1.2/lib/python3.10/site-packages/pip/_internal/utils/[logging.py](http://logging.py/)", line 177, in emit
self.console.print(renderable, overflow="ignore", crop=False, style=style)
File "/nix/store/5n0n79zxpikzj3cdx9ympanlap9pwp68-python3.10-pip-22.1.2/lib/python3.10/site-packages/pip/_vendor/rich/[console.py](http://console.py/)", line 1752, in print
extend(render(renderable, render_options))
File "/nix/store/5n0n79zxpikzj3cdx9ympanlap9pwp68-python3.10-pip-22.1.2/lib/python3.10/site-packages/pip/_vendor/rich/[console.py](http://console.py/)", line 1390, in render
for render_output in iter_render:
File "/nix/store/5n0n79zxpikzj3cdx9ympanlap9pwp68-python3.10-pip-22.1.2/lib/python3.10/site-packages/pip/_internal/utils/[logging.py](http://logging.py/)", line 134, in rich_console
for line in lines:
File "/nix/store/5n0n79zxpikzj3cdx9ympanlap9pwp68-python3.10-pip-22.1.2/lib/python3.10/site-packages/pip/_vendor/rich/[segment.py](http://segment.py/)", line 245, in split_lines
for segment in segments:
File "/nix/store/5n0n79zxpikzj3cdx9ympanlap9pwp68-python3.10-pip-22.1.2/lib/python3.10/site-packages/pip/_vendor/rich/[console.py](http://console.py/)", line 1368, in render
renderable = rich_cast(renderable)
File "/nix/store/5n0n79zxpikzj3cdx9ympanlap9pwp68-python3.10-pip-22.1.2/lib/python3.10/site-packages/pip/_vendor/rich/[protocol.py](http://protocol.py/)", line 36, in rich_cast
renderable = cast_method()
File "/nix/store/5n0n79zxpikzj3cdx9ympanlap9pwp68-python3.10-pip-22.1.2/lib/python3.10/site-packages/pip/_internal/self_outdated_[check.py](http://check.py/)", line 130, in rich
pip_cmd = get_best_invocation_for_this_pip()
File "/nix/store/5n0n79zxpikzj3cdx9ympanlap9pwp68-python3.10-pip-22.1.2/lib/python3.10/site-packages/pip/_internal/utils/[entrypoints.py](http://entrypoints.py/)", line 58, in get_best_invocation_for_this_pip
if found_executable and os.path.samefile(
File "/nix/store/ddhcwc8k9ma093n5vlpa9l617p4q2cax-python3-3.10.5/lib/python3.10/[genericpath.py](http://genericpath.py/)", line 101, in samefile
s2 = os.stat(f2)
FileNotFoundError: [Errno 2] No such file or directory: '/nix/store/ddhcwc8k9ma093n5vlpa9l617p4q2cax-python3-3.10.5/bin/pip'
```

</details>

This seems to be a known and still unsolved problem in Nixpkgs:

- https://github.com/NixOS/nixpkgs/issues/198059
- https://github.com/NixOS/nixpkgs/issues/222093

Fixing it upstream will likely unblock multiple people.

**Comment by lorenzleutgeb** [comment]
I don't understand which build fails. Please don't only provide build output but also reproducible coordinates to that build :)

```shell
$ nix build --json \
  github:armijnhemel/proximity_matcher_webservice \
  github:NixOS/nixpkgs/nixos-22.11#python3Packages.pip \
  github:NixOS/nixpkgs/nixos-23.05#python3Packages.pip \
  github:NixOS/nixpkgs/nixos-unstable#python3Packages.pip \
  | jq
```
```json
[
  {
    "drvPath": "/nix/store/b7a4311aqyygnsp3hjrn7ylmdvh1x23m-python3.10-proximity_matcher_webservice-0.0.1.drv",
    "outputs": {
      "out": "/nix/store/77lmvkr2vh0knv3b1ccfx602xjkr3sav-python3.10-proximity_matcher_webservice-0.0.1"
    }
  },
  {
    "drvPath": "/nix/store/hxsdgv9xs9806f19sjx23n2jn81l98s5-python3.10-pip-22.2.2.drv",
    "outputs": {
      "out": "/nix/store/dy4lfr6fwv3jcrbc8pbi6m97msbkpqay-python3.10-pip-22.2.2"
    }
  },
  {
    "drvPath": "/nix/store/mgz6z85h53qscwqjz45yar4bpnlrydxa-python3.10-pip-23.0.1.drv",
    "outputs": {
      "out": "/nix/store/rdsbyvrlv3glqz7w6np2y3m78cqn7d1w-python3.10-pip-23.0.1"
    }
  },
  {
    "drvPath": "/nix/store/wh62064fncf744z7pgp90vp8w59aypil-python3.10-pip-23.2.1.drv",
    "outputs": {
      "man": "/nix/store/51iz5gg6l6kkl6bgsnlnwmqbvbf0zkzq-python3.10-pip-23.2.1-man",
      "out": "/nix/store/j73ikmqhvn2sjb536bpk9khrn2cgijy3-python3.10-pip-23.2.1"
    }
  }
]

```

**Comment by fricklerhandwerk** [comment]
Good point. Updated the issue description with repro steps.

**Comment by augustebaum** [comment]
Submitted [a PR that solves the failed build](https://github.com/armijnhemel/proximity_matcher_webservice/pull/4).
